### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bueltge** [inpsyde/multilingualpress-2-to-3-migration#2]
Please change it to GPLv2+ in each context
* [x] main php
* [x] LICENSE (https://www.gnu.org/licenses/old-licenses/gpl-2.0.md)
* [ ] README
* [x] composer.json

And please remove .idea so it is not necessary for the repo.

**Comment by XedinUnknown** [comment]
Hi! I only discovered this issue quite late, as I haven't been looking for issues since there has not been a release. Therefore, some of the tasks may not be applicable at this time.

Regarding `README`, I'm not sure what you mean, as the `README.md` file does not and should not contain licensing information. This information is indicated in all contexts related to the package and the plugin, and the license text is also included in the package, as required.

As for the `.idea` directory, it allows our team and any other contributors to share and re-use project configuration. It is not necessary in order to use or develop this package, and can simply be ignored by anyone who does not need it. However, it is helpful, and therefore is included.

**Comment by bueltge** [comment]
Topic Readme: I think we should not leave a license information inside the readme, there is on top on the repository if the LICENSE file is inside the repo, thats more enough.
Topic .idea: right; currently we don't share theme. I share really often a minimum inside the .editorconfig file, like https://github.com/bueltge/marksimple/blob/master/.editorconfig

**Comment by XedinUnknown** [comment]
Ok, so good to know that with regard to the readme we are on the same page.

About the `.idea` folder, that's the PHPStorm configuration, and it includes much more than just what `.editorconfig` supports. For example:

- Rules for excluding auto-created folders from the project.
- The configuration of the environment managed by Docker.
- Database credentials for access to the virtualized DB.
- Configuration for PHPUnit integration.

These are exactly the same for everyone who is working on the project, thanks to virtualization. There is no point in each contributor having to manually re-configure their PHPStorm environment in the same way.

Of course, this is not shipped together with the plugin, and therefore for the consumer it makes no difference. Consequently, I see many more disadvantages in excluding it from the project.

**Comment by bueltge** [comment]
Yes, but not all contributors work with PhpStorm, so that we have currently the commitment to don't share them. I see also benefits to share them, but we need the feedback from all of our teams, so that we have a common commitment.

**Comment by XedinUnknown** [comment]
Well, AFAIK every developer in the product team uses PHPStorm.

Also, we both see advantages to sharing PHPStorm configuration; what are the _disadvantages_, though?

**Comment by bueltge** [comment]
>what are the disadvantages, though?

No idea, only if is not helpful, are additional data inside the repo. But, I don't know what is inside this directory, no private or personal data is important for me.
